// Official VFCD schedule snapshot. Refresh with scripts/read-schedule.cjs.
export const FESTIVAL_SCHEDULE = Object.freeze({
  source: "https://vfcd.events/schedule/",
  checkedAt: "2026-09-16T10:25:34.336Z",
  days: [
    {
      date: "2026-09-21",
      weekday: "Monday",
      events: [
        {
          id: "10990",
          title: "Circular Design Week (CDW) 2026: Fieldwork in the Mekong Delta",
          start: "08:00",
          end: "17:00",
          track: 4,
          venue: "Hau Giang – Can Tho and Tra Vinh",
          room: "",
        },
        {
          id: "10005",
          title: "Exhibition | Living Festival",
          start: "09:00",
          end: "18:00",
          track: 1,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "600",
        },
        {
          id: "10130",
          title: "Street Objects & The New Comfort",
          start: "10:00",
          end: "12:00",
          track: 3,
          venue: "Nem Space, 18/1 Ngo Thoi Nhiem, Xuan Hoa Ward, Ho Chi Minh City",
          room: "-",
        },
        {
          id: "10989",
          title: "VFCD 2026 - Opening Ceremony & Key Note",
          start: "13:00",
          end: "17:00",
          track: 2,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "600",
        },
      ],
    },
    {
      date: "2026-09-22",
      weekday: "Tuesday",
      events: [
        {
          id: "10968",
          title: "Circular Design Week (CDW) 2026: Fieldwork in the Mekong Delta",
          start: "08:00",
          end: "17:00",
          track: 4,
          venue: "Hau Giang – Can Tho and Tra Vinh",
          room: "",
        },
        {
          id: "10363",
          title: "Exhibition | Living Festival",
          start: "09:00",
          end: "18:00",
          track: 1,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "600",
        },
        {
          id: "10985",
          title: "Forum | Festival Futures Forwards",
          start: "09:00",
          end: "17:00",
          track: 2,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "250",
          sessions: [
            {
              start: "09:00",
              end: "11:30",
            },
            {
              start: "13:30",
              end: "16:00",
            },
          ],
        },
        {
          id: "10009",
          title: "Living in the BLANK",
          start: "10:00",
          end: "12:00",
          track: 3,
          venue:
            "Sanuki Daisuke Architects Studio, 120A Tran Ke Xuong Street, Phu Nhuan Ward, Ho Chi Minh City",
          room: "-",
        },
        {
          id: "10020",
          title: "22＋1",
          start: "16:00",
          end: "18:00",
          track: 3,
          venue: "Gallery Medium, 240B Pasteur Street, Xuan Hoa Ward, Ho Chi Minh City",
          room: "-",
        },
      ],
    },
    {
      date: "2026-09-23",
      weekday: "Wednesday",
      events: [
        {
          id: "11002",
          title: "Cholon Urban Walk",
          start: "06:00",
          end: "08:30",
          track: 3,
          venue: "Gathering at 34 Thap Muoi Street, Binh Tay Ward, Ho Chi Minh City. (Google Map)",
          room: "-",
        },
        {
          id: "10991",
          title: "Circular Design Week (CDW) 2026: Fieldwork in the Mekong Delta",
          start: "08:00",
          end: "17:00",
          track: 4,
          venue: "Hau Giang – Can Tho and Tra Vinh",
          room: "",
        },
        {
          id: "11004",
          title: "When the City Is Mapped Differently",
          start: "09:00",
          end: null,
          track: 3,
          venue:
            "Gathering at Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City.",
          room: "-",
        },
        {
          id: "10980",
          title: "Exhibition | Living Festival",
          start: "09:00",
          end: "18:00",
          track: 1,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "600",
        },
        {
          id: "11005",
          title: "VNx Panel | Learning Beyond Classroom",
          start: "09:30",
          end: "11:30",
          track: 5,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "250",
        },
        {
          id: "10129",
          title:
            "The Design Intelligence Lab: Codifying Design Intelligence through Cross-Cultural Architectural Practice",
          start: "10:00",
          end: "13:00",
          track: 3,
          venue:
            "Out2Design Studio, Tropic Garden, 49 Street No. 66, An Khanh Ward, Ho Chi Minh City, Block C2, Ground Floor",
          room: "-",
        },
        {
          id: "10019",
          title:
            "Living Threads - Fragmented Scrolls: Reflective Needlecraft in the Cracks of Everyday Life",
          start: "10:30",
          end: "17:00",
          track: 3,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh, Xom Chieu, Ho Chi Minh",
          room: "600 (small room)",
          sessions: [
            {
              start: "10:30",
              end: "12:00",
            },
            {
              start: "15:30",
              end: "17:00",
            },
          ],
        },
        {
          id: "10007",
          title: "The Lab: An Evolving Practice",
          start: "14:00",
          end: "16:00",
          track: 3,
          venue: "The Lab, 02 Le Ngo Cat Street, Xuan Hoa Ward, Ho Chi Minh City",
          room: "-",
        },
        {
          id: "10131",
          title: "Short Film Session",
          start: "14:00",
          end: "17:00",
          track: 3,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "250",
        },
      ],
    },
    {
      date: "2026-09-24",
      weekday: "Thursday",
      events: [
        {
          id: "10969",
          title:
            "Circular Design Week (CDW) 2026 Commons: Panel discussions and co-creating the Alluvial Wall",
          start: "09:00",
          end: "17:00",
          track: 4,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "100 - 250",
        },
        {
          id: "10981",
          title: "Exhibition | Living Festival",
          start: "09:00",
          end: "18:00",
          track: 1,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "600",
        },
        {
          id: "10018",
          title: "Design Is a Verb",
          start: "10:00",
          end: "12:00",
          track: 3,
          venue:
            "Laita Design Studio, Hung Phu Residential Area, 36 D8 Street, Phuoc Long Ward, Ho Chi Minh City",
          room: "-",
        },
        {
          id: "10008",
          title: "Learning [From] Everyday",
          start: "14:00",
          end: "16:00",
          track: 3,
          venue:
            "TOTO Showroom, 1A Pham Ngoc Thach Street, Sai Gon Ward, Ho Chi Minh City, Level 03",
          room: "-",
        },
      ],
    },
    {
      date: "2026-09-25",
      weekday: "Friday",
      events: [
        {
          id: "11006",
          title:
            "Circular Design Week (CDW) 2026 Commons: Panel discussions and co-creating the Alluvial Wall",
          start: "09:00",
          end: "17:00",
          track: 4,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "100 - 250",
        },
        {
          id: "10982",
          title: "Exhibition | Living Festival",
          start: "09:00",
          end: "18:00",
          track: 1,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "600",
        },
        {
          id: "10006",
          title: "Reviving Urban Memory: Adaptive Reuse and the Living City at Tempo Nexus",
          start: "10:00",
          end: "12:00",
          track: 3,
          venue: "Tempo Nexus Reading Room, 130 Pasteur Street, Saigon Ward, Ho Chi Minh City",
          room: "-",
        },
        {
          id: "11007",
          title: "Do Baskets Dream Of ___>",
          start: "20:00",
          end: "21:00",
          track: 3,
          venue: "ARTSPACE (S6), 01 Truong Dinh Hoi Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "-",
        },
      ],
    },
    {
      date: "2026-09-26",
      weekday: "Saturday",
      events: [
        {
          id: "10984",
          title: "Exhibition | Living Festival",
          start: "09:00",
          end: "18:00",
          track: 1,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "600",
        },
        {
          id: "11009",
          title: "Experimental Digital Arts",
          start: "10:00",
          end: "13:00",
          track: 3,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "250",
        },
        {
          id: "11010",
          title: "Hao Si Phuong Gallery",
          start: "10:00",
          end: "13:00",
          track: 3,
          venue:
            "AD+ studio, Hao Sy Phuong Apartment Building, 206 Tran Hung Dao Street, Cho Lon Ward, Ho Chi Minh City",
          room: "-",
        },
        {
          id: "11011",
          title: "Mạch Ngầm [counter-place]",
          start: "14:00",
          end: "16:00",
          track: 3,
          venue:
            "Nguyễn Art Foundation, EMASI Nam Long, Nam Long Residential Area, 147 Street No.8, Tan Thuan Ward, Ho Chi Minh City",
          room: "-",
        },
        {
          id: "11008",
          title: "Creative Expression Session",
          start: "14:00",
          end: "17:00",
          track: 3,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "250",
        },
      ],
    },
    {
      date: "2026-09-27",
      weekday: "Sunday",
      events: [
        {
          id: "10983",
          title: "Exhibition | Living Festival",
          start: "09:00",
          end: "18:00",
          track: 1,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "600",
        },
        {
          id: "10576",
          title: "Invisible Reflection",
          start: "10:00",
          end: "12:00",
          track: 3,
          venue:
            "Vin Gallery, Amanaki Thao Dien, 10 Phan Dang Giai Street, An Khanh Ward, Ho Chi Minh City, Floor 07.",
          room: "-",
        },
        {
          id: "11013",
          title: "Performance Art",
          start: "10:00",
          end: "13:00",
          track: 3,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "250",
        },
        {
          id: "11016",
          title: "Living Space: How Architecture Shapes the Way We Live",
          start: "14:00",
          end: "16:00",
          track: 3,
          venue: "Kaze Studio, 25C Nguyen Duy Hieu Street, An Khanh Ward, Ho Chi Minh City",
          room: "-",
        },
        {
          id: "11014",
          title: "Urban Art",
          start: "14:00",
          end: "17:00",
          track: 3,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "100",
        },
        {
          id: "11012",
          title: "Breathe The Idea: The thinking, making and shaping behind VFCD’s visual identity",
          start: "17:00",
          end: "19:00",
          track: 3,
          venue: "Nina Next Space, 180/1 Nguyen Tat Thanh Street, Xom Chieu Ward, Ho Chi Minh City",
          room: "250",
        },
      ],
    },
  ],
});
